In [64]:
print("welcome to Python!")

welcome to Python


# Python data types, methods for moving data, functions

#### Interested in how to use markdown in jupyter notebook? (support math)

## A. Get familiar with jupyter notebook

### 1.  Try to create a code block under this line.

### 2. Try to move the code block above to below.

### 3. Try to write 1+1 in the code block above, run it (shift+enter or ctl+enter) , then cut it, then paste it below.

### Nice Work!

### Jupyter notebook have autocomplete function. Try to press "tab" at the end of the second line in code block below:

In [ ]:
import numpy as np
np.arr

### Jupter notebook holds magic self-carring function: e.g. timing a program use %%time at the beginning

In [140]:
%%time
import time
summ = 0
for i in range(10):
    summ = summ + i
    time.sleep(0.1)

Wall time: 1.01 s


## B. Python import of modules

In [29]:
import numpy 
numpy.sqrt(9)

3.0

In [30]:
sqrt(9)

NameError: name 'sqrt' is not defined

In [31]:
import numpy as np
np.sqrt(9)

3.0

## Python variables and type

### Variables for computation: scalar (int and float), vector (array and matrix) 

In [24]:
#scalar
a = 1
b = 1.0
print(type(a))
print(type(b))

<class 'int'>
<class 'float'>


In [25]:
a+b

2.0

In [26]:
type(a+b)

float

In [32]:
#vector
import numpy as np
'''
Core usage to use np.array():
variable-name = np.array([xxx])
'''
a = np.array([ 1,2,3,4 ]) # vector without dimension

In [33]:
a

array([1, 2, 3, 4])

In [34]:
a.shape

(4,)

In [37]:
b = np.array([ [1,2,3,4] ]) # vector with dimension 1*4
c = np.array([ [1],[2],[3],[4] ]) # vector with dimesion 4*1
### In the braket, each one more braket means each row.

In [40]:
b

array([[1, 2, 3, 4]])

In [41]:
b.shape

(1, 4)

In [36]:
c

array([[1],
       [2],
       [3],
       [4]])

In [42]:
c.shape

(4, 1)

In [43]:
b.T

array([[1],
       [2],
       [3],
       [4]])

In [44]:
d = np.array([ [1,2,3], [4,5,6] ]) # matrix 
d

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
d.shape

(2, 3)

### Variable computation: add, subtract, multiply, dot, divide, inverse

In [48]:
e = d
# add: element-wise
e+d

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [50]:
np.add(e,d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [52]:
# subtratc: element-wise
e-d

array([[0, 0, 0],
       [0, 0, 0]])

In [53]:
np.subtract(e,d)

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
# multiply: element-wise
e*d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [55]:
np.multiply(e,d)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [56]:
# dot: matrix multiplication

$$\begin{array}{l}
{\rm{e}} = \left( {\begin{array}{*{20}{c}}
{\begin{array}{*{20}{c}}
1&2&3
\end{array}}\\
{\begin{array}{*{20}{c}}
4&5&6
\end{array}}
\end{array}} \right) \in {R^{2*3}}\\
d = \left( {\begin{array}{*{20}{c}}
{\begin{array}{*{20}{c}}
1&2&3
\end{array}}\\
{\begin{array}{*{20}{c}}
4&5&6
\end{array}}
\end{array}} \right) \in {R^{2*3}} \Rightarrow {d^T} = \left( {\begin{array}{*{20}{c}}
{\begin{array}{*{20}{c}}
1\\
2\\
3
\end{array}}&{\begin{array}{*{20}{c}}
4\\
5\\
6
\end{array}}
\end{array}} \right) \in {R^{3*2}}\\
e{d^T} = \left( {\begin{array}{*{20}{c}}
{1*1 + 2*2 + 3*3}&{1*4 + 2*5 + 3*6}\\
{4*1 + 5*2 + 6*3}&{4*4 + 5*5 + 6*6}
\end{array}} \right) = ?
\end{array}$$

In [60]:
dt = d.T
dt

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
dt = d.reshape(3,2)
dt

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
np.dot(e,dt)

array([[22, 28],
       [49, 64]])

In [66]:
# divide: element-wise
e/d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.divide(e,d)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
# inverse of matrix

#### If given $A \in {R^{n*n}}$, the inverse of $A$, denoted as ${A^{ - 1}} \in {R^{n*n}}$, is the matrix such that ${A^{ - 1}}A = A{A^{ - 1}} = I$.

In [69]:
a = np.array([ [1,2], [3,4] ])
a

array([[1, 2],
       [3, 4]])

In [70]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Variables for logic: boolean type

In [75]:
1 = 2

SyntaxError: can't assign to literal (<ipython-input-75-c0ab9e3898ea>, line 1)

In [76]:
1 == 2

False

In [77]:
1 >= 2 

False

In [79]:
1 >= 1

True

In [80]:
1 != 2

True

In [81]:
1 != 1

False

In [84]:
a = True
a

True

In [85]:
True == False

False

In [88]:
True * 5

5

In [89]:
True + 1 

2

In [90]:
True == 1

True

In [91]:
False == 0

True

### Boolean operations

In [92]:
a = True
b = False

In [93]:
a & b

False

In [98]:
a and b

False

In [94]:
a | b

True

In [99]:
a or b

True

In [97]:
x = 3
(x>=1) & (x<=5) # will be used in controling statement

True

### Variables as container: string, list, tuple, dictionary

#### string

In [116]:
a = 'this is string'
b = "this is string"
c = '''this is string'''
a

'this is string'

In [110]:
a == b 

True

In [111]:
b == c

True

In [113]:
c = "
this is string
"

SyntaxError: EOL while scanning string literal (<ipython-input-113-3c250d4eb7a9>, line 1)

In [122]:
c = '''
this is long string'''

In [123]:
c

'\nthis is long string'

In [124]:
d = '\nthis is long string'

In [125]:
c == d

True

In [126]:
e = '''Here "is a 'complex string'"'''

In [127]:
e

'Here "is a \'complex string\'"'

In [153]:
# string operation

In [154]:
'a' + 'b'

'ab'

In [143]:
'a'.upper()

'A'

In [150]:
'this is mine'.upper()

'THIS IS MINE'

In [151]:
'this is mine'.capitalize()

'This is mine'

In [152]:
'a b c'.split(' ')

['a', 'b', 'c']

In [160]:
'this is an example'.replace('is','was')

'thwas was an example'

In [156]:
# string indexing

In [157]:
'this is me'[0] # In python 0 also represent the first, then 1 is the second

't'

In [158]:
'this is me'[1]

'h'

In [159]:
'this is me'[0:3] # 0:3 stands for 'from 0, count 3 element to output, so the last index is 2'.

'thi'

In [167]:
'this is me'[:3] # the first position is missing, the default is 0

'thi'

In [168]:
'this is me'[3:] # the last position is missing, it stands for "from the 4th position to the last"

's is me'

In [165]:
'this is me'[-1] # -1 stands for the last 1 elemenet

'e'

In [171]:
'this is me'[:] # both start and end are missing, represent the entire str.

'this is me'

In [161]:
#e.g.
text = 'this is an example'
text.replace('is','was')

'thwas was an example'

In [173]:
## we dont want to replace the first 'is', so:
text[4:].replace('is','was')
text

'this is an example'

#### List

In [176]:
## List is container created by braket, which accepts inputs as all kind of datatype
a = [1,2,3,4]
type(a)

list

In [177]:
a = [1,2,'this','that',['even another list']]

In [178]:
a

[1, 2, 'this', 'that', ['even another list']]

In [179]:
# list is callable, so you can call each element by index
a[0]

1

In [181]:
a[-1]

['even another list']

In [184]:
# list is changeable, so you can change each element easily.
a[-1] = 1

In [185]:
a

[1, 2, 'this', 'that', 1]

In [186]:
## list operarion

In [188]:
b = [1,2,4,4]
c = a + b
c

[1, 2, 'this', 'that', 1, 1, 2, 4, 4]

In [193]:
[1,2,3] * 2

[1, 2, 3, 1, 2, 3]

In [194]:
c.append(5)

In [195]:
c

[1, 2, 'this', 'that', 1, 1, 2, 4, 4, 5]

In [196]:
c.insert(2,6) # put element "6" into the position with index 2.
c

[1, 2, 6, 'this', 'that', 1, 1, 2, 4, 4, 5]

In [200]:
c.count(4) # how many 4 is in c

2

In [203]:
c.reverse()
c

[5, 4, 4, 2, 1, 1, 'that', 'this', 6, 2, 1]

In [204]:
c.remove(1) # only remove the first 1 from the left to right
c

[5, 4, 4, 2, 1, 'that', 'this', 6, 2, 1]

In [205]:
c.pop(0) # given 0 as the certain index position, remove the element on 0 as the index
c

[4, 4, 2, 1, 'that', 'this', 6, 2, 1]

#### tuple

In [224]:
# tuple is similar with list, while create by parentheses
a = (1,2,5,'this','that',4,3)
# if parentheses is missing, the tuple is default
b = 1,4

In [225]:
a

(1, 2, 5, 'this', 'that', 4, 3)

In [226]:
b

(1, 4)

In [227]:
# tuple v.s. list
# tuple is more stable than list, you can't chang items in it by calling index. e.g.
b[0] = 2

TypeError: 'tuple' object does not support item assignment

In [228]:
# and also we dont have various of functions like .append .insert .remove . pop
# so what can we do if we want to change it enforcely?
# tansfer!

In [229]:
a_after = list(a) # list() is used to transfer a callable objective (string, tuple, or even dictionary) into list
a_after.remove('this')
a = tuple(a_after) # tuple() is used to transfer a callable objective (string, list, or even dictionary) into tuple
a

(1, 2, 5, 'that', 4, 3)

#### Dictionary

In [244]:
# Dictionary can be treated as a special type of list. In list, we have many elements, 
# and their indexes are nature numbers: 0,1,2,... But sometimes, we want a much more complicated index, e.g. string type.
a = {'name':'Bruce','age':23,'job':'student'} 
# dictionary is created by curly bracket, containing pairs of key,colon,value elements, saperated by comma 

In [245]:
## to obtain the value, we use the key as the index:
a['name']

'Bruce'

In [246]:
## or
a.get('name')

'Bruce'

In [247]:
## Sometimes, it there is no key name that we are searching, and also we dont want the program to throw out error, we use
a.get('fack_key','No key exist')

'No key exist'

In [248]:
## the items function return a list a tuple that consists every (key,value) pair
a.items()

dict_items([('name', 'Bruce'), ('age', 23), ('job', 'student')])

In [249]:
## to add a new key:value item in dictionary, we use:
# dictionary_name[key] = value
a['university'] = 'uconn'
a

{'name': 'Bruce', 'age': 23, 'job': 'student', 'university': 'uconn'}

In [250]:
# or also, we can use the .update() function for dictionary to add new element:
a.update({'state':'CT'})
a

{'name': 'Bruce',
 'age': 23,
 'job': 'student',
 'university': 'uconn',
 'state': 'CT'}

In [251]:
# to delete element in dictinary, we use del and call the key:
del a['state']
a

{'name': 'Bruce', 'age': 23, 'job': 'student', 'university': 'uconn'}

### (Important) Data indexing and moving

#### Have you ever used R before? U may remember there is something in R that is similar with excel table, holding column names and even row names. That is the "Dataframe". In Python, we also have dataframe, and is really frequently used.

In [256]:
# To create dataframe:
import pandas as pd
# method 1: create from dictionary with {'column name1':[column values],'column name2':[column values],...}
data = pd.DataFrame({'x':[0,1,2,3,4],'y':[5,6,7,8,9]})
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [257]:
# method 2: create from numpy array with columns name
data_values = np.array([[0,5],[1,6],[2,7],[3,8],[4,9]])
data = pd.DataFrame(data=data_values,columns=['x','y'])
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [258]:
# method 3: loading from cvs, excel, or even txt
data = pd.read_csv('data_file.csv')
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [259]:
data = pd.read_csv('data_file.txt',sep=' ')
data

x  y
0  0  5
1  1  6
2  2  7
3  3  8
4  4  9

In [260]:
## after creating the dataframe you can always change the row name, i.e. the index by:

In [261]:
data.index = ['a','b','c','d','e']

In [262]:
data

x  y
a  0  5
b  1  6
c  2  7
d  3  8
e  4  9