In [6]:
import tensorflow as tf
import tensorflow.compat.v1 as tfv1
tf.__version__

'2.1.0'

In [7]:
s = tf.constant(2)
m = tf.constant([[1,2],[3,4]])

In [8]:
g = tf.Graph()
with g.as_default():
    s = tf.constant(2)
    m = tf.constant([[1,2],[3,4]])
    mmul = s*m
g

In [9]:
with tfv1.Session(graph=g) as sess:
    print(sess.run(mmul))

[[2 4]
 [6 8]]


In [15]:
w = tf.Variable(tf.ones((2,2)))

In [11]:
with tfv1.Session() as sess:
    print(sess.run(w))
    # It will give u an error because you haven't initialize it.

FailedPreconditionError: Error while reading resource variable Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/Variable)
	 [[node Variable/Read/ReadVariableOp (defined at <ipython-input-10-4dd64bbfa558>:1) ]]

Original stack trace for 'Variable/Read/ReadVariableOp':
  File "C:\Users\jinju\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jinju\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\jinju\Anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\jinju\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 563, in start
    self.io_loop.start()
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\jinju\Anaconda3\lib\asyncio\base_events.py", line 534, in run_forever
    self._run_once()
  File "C:\Users\jinju\Anaconda3\lib\asyncio\base_events.py", line 1771, in _run_once
    handle._run()
  File "C:\Users\jinju\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2855, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in _run_cell
    return runner(coro)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\jinju\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-4dd64bbfa558>", line 1, in <module>
    w = tf.Variable(tf.ones(2,2))
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\ops\variables.py", line 260, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\ops\variables.py", line 254, in _variable_v2_call
    shape=shape)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\ops\variables.py", line 235, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 2645, in default_variable_creator_v2
    shape=shape)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\ops\variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 1411, in __init__
    distribute_strategy=distribute_strategy)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 1592, in _init_from_args
    value = gen_resource_variable_ops.read_variable_op(handle, dtype)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_resource_variable_ops.py", line 482, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "C:\Users\jinju\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()


In [20]:
with tfv1.Session() as sess:
    sess.run(tfv1.global_variables_initializer())
    print(sess.run(w))

[[1. 1.]
 [1. 1.]]


In [21]:
with tfv1.Session() as sess:
    sess.run(tfv1.global_variables_initializer())
    print(sess.run(w))
    sess.run(w.assign(tf.zeros((2,2))))
    print(sess.run(w))

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [31]:
import numpy as np
node1 = tfv1.placeholder(tf.float32,shape = [1,2])
node2 = tfv1.placeholder(tf.float32,shape = [1,2])
w_linear = tf.matmul(node1,w) + node2
with tfv1.Session() as sess:
    sess.run(tfv1.global_variables_initializer())
    print(sess.run(w))
    print(sess.run(w_linear,feed_dict={node1:np.matrix([1.0,2.0]),node2:np.matrix([1.0,2.0])}))

[[1. 1.]
 [1. 1.]]
[[4. 5.]]


$\left( {\begin{array}{*{20}{c}}
{\rm{4}}&{\rm{5}}
\end{array}} \right){\rm{ = }}\left( {\begin{array}{*{20}{c}}
{\rm{1}}&{\rm{2}}
\end{array}} \right)\left( {\begin{array}{*{20}{c}}
{\rm{1}}&{\rm{1}}\\
{\rm{1}}&{\rm{1}}
\end{array}} \right){\rm{ + }}\left( {\begin{array}{*{20}{c}}
{\rm{1}}&{\rm{2}}
\end{array}} \right)$